#!/bin/sh
### parameter reference: Use Model-Based Analysis of ChIP-Seq (MACS) to Analyze Short Reads Generated by Sequencing Protein–DNA Interactions in Embryonic Stem Cells, https://link.springer.com/protocol/10.1007/978-1-4939-0512-6_4#Sec14

cd /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shCont/shCont_macs2
rm -rf ./*
macs2 callpeak --broad -B -g hs -t /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shCont/IP_rep1/Hela_ChIP-seq_shCont_IP_rep1.fastq.sorted.bam \
  /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shCont/IP_rep2/Hela_ChIP-seq_shCont_IP_rep2.fastq.sorted.bam \
  -c /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shCont/input_rep1/Hela_ChIP-seq_shCont_input_rep1.fastq.sorted.bam \
  /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shCont/input_rep2/Hela_ChIP-seq_shCont_input_rep2.fastq.sorted.bam \
  -n shCont_macs2 > shCont.macs2.log 2>&1 &

cd /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shSetD2/shSetD2_macs2
rm -rf ./*
macs2 callpeak --broad -B -g hs -t /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shSetD2/IP_rep1/Hela_ChIP-seq_shSetD2_IP_rep1.fastq.sorted.bam \
  /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shSetD2/IP_rep2/Hela_ChIP-seq_shSetD2_IP_rep2.fastq.sorted.bam \
  -c /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shSetD2/input_rep1/Hela_ChIP-seq_shSetD2_input_rep1.fastq.sorted.bam \
  /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shSetD2/input_rep2/Hela_ChIP-seq_shSetD2_input_rep2.fastq.sorted.bam \
  -n shSetD2_macs2 > shSetD2.macs2.log 2>&1 &

cd /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shWTAP/shWTAP_macs2
rm -rf ./*
macs2 callpeak --broad -B -g hs -t /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shWTAP/IP_rep1/Hela_ChIP-seq_shWTAP_IP_rep1.fastq.sorted.bam \
  -c /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shWTAP/input_rep1/Hela_ChIP-seq_shWTAP_input_rep1.fastq.sorted.bam \
  -n shWTAP_macs2 > shWTAP.macs2.log 2>&1 &

cd /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shM3/shM3_macs2
rm -rf ./*
macs2 callpeak --broad -B -g hs -t /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shM3/IP_rep1/Hela_ChIP-seq_shM3_IP_rep1.fastq.sorted.bam \
  -c /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shM3/input_rep1/Hela_ChIP-seq_shM3_input_rep1.fastq.sorted.bam \
  -n shM3_macs2 > shM3.macs2.log 2>&1 &

cd /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shM14/shM14_macs2
rm -rf ./*
macs2 callpeak --broad -B -g hs -t /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shM14/IP_rep1/Hela_ChIP-seq_shM14_IP_rep1.fastq.sorted.bam \
  -c /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shM14/input_rep1/Hela_ChIP-seq_shM14_input_rep1.fastq.sorted.bam \
  -n shM14_macs2 > shM14.macs2.log 2>&1 &

cd /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/bash

############# call peaks with --nomodel --extsize 147

mkdir /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shCont/shCont_macs2-nomodel
cd /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shCont/shCont_macs2-nomodel
rm -rf ./*
macs2 callpeak --broad -B --nomodel --extsize 147 -g hs -t /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shCont/IP_rep1/Hela_ChIP-seq_shCont_IP_rep1.fastq.sorted.bam \
  /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shCont/IP_rep2/Hela_ChIP-seq_shCont_IP_rep2.fastq.sorted.bam \
  -c /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shCont/input_rep1/Hela_ChIP-seq_shCont_input_rep1.fastq.sorted.bam \
  /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shCont/input_rep2/Hela_ChIP-seq_shCont_input_rep2.fastq.sorted.bam \
  -n shCont_macs2 > shCont.macs2.log 2>&1 &

mkdir /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shSetD2/shSetD2_macs2-nomodel
cd /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shSetD2/shSetD2_macs2-nomodel
rm -rf ./*
macs2 callpeak --broad -B --nomodel --extsize 147 -g hs -t /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shSetD2/IP_rep1/Hela_ChIP-seq_shSetD2_IP_rep1.fastq.sorted.bam \
  /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shSetD2/IP_rep2/Hela_ChIP-seq_shSetD2_IP_rep2.fastq.sorted.bam \
  -c /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shSetD2/input_rep1/Hela_ChIP-seq_shSetD2_input_rep1.fastq.sorted.bam \
  /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shSetD2/input_rep2/Hela_ChIP-seq_shSetD2_input_rep2.fastq.sorted.bam \
  -n shSetD2_macs2 > shSetD2.macs2.log 2>&1 &

mkdir /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shWTAP/shWTAP_macs2-nomodel
cd /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shWTAP/shWTAP_macs2-nomodel
rm -rf ./*
macs2 callpeak --broad -B --nomodel --extsize 147 -g hs -t /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shWTAP/IP_rep1/Hela_ChIP-seq_shWTAP_IP_rep1.fastq.sorted.bam \
  -c /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shWTAP/input_rep1/Hela_ChIP-seq_shWTAP_input_rep1.fastq.sorted.bam \
  -n shWTAP_macs2 > shWTAP.macs2.log 2>&1 &

mkdir /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shM3/shM3_macs2-nomodel
cd /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shM3/shM3_macs2-nomodel
rm -rf ./*
macs2 callpeak --broad -B --nomodel --extsize 147 -g hs -t /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shM3/IP_rep1/Hela_ChIP-seq_shM3_IP_rep1.fastq.sorted.bam \
  -c /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shM3/input_rep1/Hela_ChIP-seq_shM3_input_rep1.fastq.sorted.bam \
  -n shM3_macs2 > shM3.macs2.log 2>&1 &

mkdir /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shM14/shM14_macs2-nomodel
cd /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shM14/shM14_macs2-nomodel
rm -rf ./*
macs2 callpeak --broad -B --nomodel --extsize 147 -g hs -t /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shM14/IP_rep1/Hela_ChIP-seq_shM14_IP_rep1.fastq.sorted.bam \
  -c /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/shM14/input_rep1/Hela_ChIP-seq_shM14_input_rep1.fastq.sorted.bam \
  -n shM14_macs2 > shM14.macs2.log 2>&1 &

cd /data/zhoukr/hhl_setd2_m6a/Hela_ChIP-seq/bash


