#!/bin/sh
## ref. Identifying ChIP-seq enrichment using MACS, Nat Protoc., 2012, --shiftsize was set as recommended by "Use Model-Based Analysis of ChIP-Seq (MACS) to Analyze Short Reads Generated by Sequencing Protein–DNA Interactions in Embryonic Stem Cells"

rm -rf /data/zhoukr/hhl_setd2_m6a/mouse_ESCs_ChIP-seq/Ctrl_D0/macs1.4-merge
mkdir /data/zhoukr/hhl_setd2_m6a/mouse_ESCs_ChIP-seq/Ctrl_D0/macs1.4-merge
cd /data/zhoukr/hhl_setd2_m6a/mouse_ESCs_ChIP-seq/Ctrl_D0/macs1.4-merge
macs14 -t ../mESCs_ChIP-seq_Ctrl_D0_ChIP.merge.bam -c ../mESCs_ChIP-seq_Ctrl_D0_input.merge.bam  -g mm -n shCont --nomodel --shiftsize 147 -B -S --call-subpeaks > shCont.merge.macs14.log 2>&1 &

rm -rf /data/zhoukr/hhl_setd2_m6a/mouse_ESCs_ChIP-seq/SetD2-KD_D0/macs1.4-merge
mkdir /data/zhoukr/hhl_setd2_m6a/mouse_ESCs_ChIP-seq/SetD2-KD_D0/macs1.4-merge
cd /data/zhoukr/hhl_setd2_m6a/mouse_ESCs_ChIP-seq/SetD2-KD_D0/macs1.4-merge
macs14 -t ../mESCs_ChIP-seq_SetD2-KD_D0_ChIP.merge.bam -c ../mESCs_ChIP-seq_SetD2-KD_D0_input.merge.bam  -g mm -n shSetD2 --nomodel --shiftsize 147 -B -S --call-subpeaks > shSetD2.merge.macs14.log 2>&1 &
